apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pqc-jwt

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:

    - job_name: auth
      static_configs:
      - targets:
          - auth-service:8000

    - job_name: user
      static_configs:
      - targets:
          - user-service:8000