events {}

http {
    upstream auth {
        server auth-service:8000;
    }

    upstream user {
        server user-service:8000;
    }

    server {
        listen 80;

        location /login {
            proxy_pass http://auth/login;
        }

        location /protected {
            proxy_pass http://user/protected;
        }
    }
}